
spring:
  application:
    name: DOAN
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true

  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.mail: DEBUG
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MY_EMAIL}
    password: ${MY_PASSWORD_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
