spring:
  application:
    name: DOAN
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true
  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.mail: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.tool.schema: DEBUG
      org.springframework.oauth2: DEBUG
      org.springframework.web: DEBUG
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MY_EMAIL}
    password: ${MY_PASSWORD_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:5173/auth/callback/google"
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            scope:
              - openid
              - profile
              - email
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-name-attribute: sub
#  cloud:
  gcp:
    credentials:
      location: E:\serviceAccountKey.json
#        api-key: AIzaSyBeKDAB-ExkmehT8tTsPyq1b9BKOQm3KZM
  openai:
    api:
      key: ${OPENAI_API_KEY}
vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:5173/loading